[package]
name = "notify"
version = "2.0.0"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
  "Michael Maurizi <michael.maurizi@gmail.com>",
  "Pierre Baillet <oct@zoy.org>",
  "ShuYu Wang <andelf@gmail.com>",
]

description = "Cross-platform filesystem notification library"
homepage = "https://github.com/passcod/rsnotify"
repository = "https://github.com/passcod/rsnotify.git"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "events",
  "filesystem",
  "notify",
  "watch",
]

[dependencies]
bitflags = "*"
libc = "*"
log = "*"
time = "*"
walker = "^1.0.0"

[target.x86_64-unknown-linux-gnu.dependencies.inotify]
version = "^0.1"

[target.x86_64-apple-darwin.dependencies.fsevent-sys]
version = "^0.1"

[target.i686-pc-windows-gnu]
dependencies = { winapi = "0.1", kernel32-sys = "0.1" }

[target.x86_64-pc-windows-gnu]
dependencies = { winapi = "0.1", kernel32-sys = "0.1" }
